[project]
name = "MCP-geo"
dynamic = ["version"]
description = "Geocoding MCP server with GeoPY!"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geopy>=2.4.1",
    "mcp[cli]>=1.2.0",
    "click>=8.0.0",
]


[tool.hatch.version]
path = "geo.py"
